# Generated by Django 2.2.28 on 2022-07-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscoordinator',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='authorizedusers',
            name='phone',
        ),
    ]
